# Generated by Django 2.0.5 on 2018-05-06 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('secondname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('physical_address', models.CharField(max_length=250)),
                ('postaladdress', models.CharField(max_length=250)),
                ('phonenumber1', models.CharField(max_length=10)),
                ('phonenumber2', models.CharField(max_length=10)),
                ('phonenumber3', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=250)),
                ('birthdate', models.DateField()),
                ('nationality', models.CharField(max_length=250)),
                ('spousename', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marriage', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=10)),
                ('occupation', models.CharField(choices=[('employed', 'Employed'), ('business', 'Business'), ('epxertise', 'Expertise'), ('student', 'Student'), ('others', 'Others')], max_length=10)),
                ('occupationdetails', models.CharField(max_length=250)),
                ('languages', models.CharField(choices=[('english', 'English'), ('swahili', 'Swahili'), ('french', 'French'), ('others', 'Others')], max_length=10)),
                ('datejoiningcapstone', models.DateField()),
                ('fellowshipname', models.CharField(max_length=250)),
                ('bornagain', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('filledhollyspirit', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('baptisedimmersion', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('servinggoddept', models.CharField(max_length=250)),
                ('havingchildren', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
