# Generated by Django 2.0.5 on 2018-05-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstonemembers', '0002_auto_20180506_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersdetails',
            name='phonenumber1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='membersdetails',
            name='phonenumber2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='membersdetails',
            name='phonenumber3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
