# Generated by Django 2.0.5 on 2018-05-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstonemembers', '0003_auto_20180506_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersdetails',
            name='body',
        ),
        migrations.RemoveField(
            model_name='membersdetails',
            name='slug',
        ),
        migrations.AlterField(
            model_name='membersdetails',
            name='postaladdress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
